//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Automated_Customer_Notifications.API_ODFL {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TraceSoapBinding", Namespace="http://trace.odfl.com")]
    public partial class TraceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getTraceDataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TraceService() {
            this.Url = global::Automated_Customer_Notifications.Properties.Settings.Default.Automated_Customer_Notifications_API_ODFL_TraceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getTraceDataCompletedEventHandler getTraceDataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://trace.odfl.com", ResponseNamespace="http://trace.odfl.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("getTraceDataReturn", IsNullable=true)]
        public TraceResult getTraceData([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pro, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string type) {
            object[] results = this.Invoke("getTraceData", new object[] {
                        pro,
                        type});
            return ((TraceResult)(results[0]));
        }
        
        /// <remarks/>
        public void getTraceDataAsync(string pro, string type) {
            this.getTraceDataAsync(pro, type, null);
        }
        
        /// <remarks/>
        public void getTraceDataAsync(string pro, string type, object userState) {
            if ((this.getTraceDataOperationCompleted == null)) {
                this.getTraceDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTraceDataOperationCompleted);
            }
            this.InvokeAsync("getTraceData", new object[] {
                        pro,
                        type}, this.getTraceDataOperationCompleted, userState);
        }
        
        private void OngetTraceDataOperationCompleted(object arg) {
            if ((this.getTraceDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTraceDataCompleted(this, new getTraceDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://trace.odfl.com")]
    public partial class TraceResult {
        
        private string proNumField;
        
        private string proDateField;
        
        private string statusCodeField;
        
        private string statusField;
        
        private string appointmentField;
        
        private string piecesField;
        
        private string weightField;
        
        private string poField;
        
        private string bolField;
        
        private string trailerField;
        
        private string signatureField;
        
        private string origTerminalField;
        
        private string origAddressField;
        
        private string origStateField;
        
        private string origNameField;
        
        private string origCityField;
        
        private string origZipField;
        
        private string origPhoneField;
        
        private string origFaxField;
        
        private string destTerminalField;
        
        private string destAddressField;
        
        private string destStateField;
        
        private string destNameField;
        
        private string destCityField;
        
        private string destZipField;
        
        private string destPhoneField;
        
        private string destFaxField;
        
        private string deliveredField;
        
        private string urlField;
        
        private string typeField;
        
        private string scacField;
        
        private string errorMessageField;
        
        private string guaranteedField;
        
        private string callField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string proNum {
            get {
                return this.proNumField;
            }
            set {
                this.proNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string proDate {
            get {
                return this.proDateField;
            }
            set {
                this.proDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string appointment {
            get {
                return this.appointmentField;
            }
            set {
                this.appointmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pieces {
            get {
                return this.piecesField;
            }
            set {
                this.piecesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string po {
            get {
                return this.poField;
            }
            set {
                this.poField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string bol {
            get {
                return this.bolField;
            }
            set {
                this.bolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string trailer {
            get {
                return this.trailerField;
            }
            set {
                this.trailerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string origTerminal {
            get {
                return this.origTerminalField;
            }
            set {
                this.origTerminalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string origAddress {
            get {
                return this.origAddressField;
            }
            set {
                this.origAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string origState {
            get {
                return this.origStateField;
            }
            set {
                this.origStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string origName {
            get {
                return this.origNameField;
            }
            set {
                this.origNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string origCity {
            get {
                return this.origCityField;
            }
            set {
                this.origCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string origZip {
            get {
                return this.origZipField;
            }
            set {
                this.origZipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string origPhone {
            get {
                return this.origPhoneField;
            }
            set {
                this.origPhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string origFax {
            get {
                return this.origFaxField;
            }
            set {
                this.origFaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string destTerminal {
            get {
                return this.destTerminalField;
            }
            set {
                this.destTerminalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string destAddress {
            get {
                return this.destAddressField;
            }
            set {
                this.destAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string destState {
            get {
                return this.destStateField;
            }
            set {
                this.destStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string destName {
            get {
                return this.destNameField;
            }
            set {
                this.destNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string destCity {
            get {
                return this.destCityField;
            }
            set {
                this.destCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string destZip {
            get {
                return this.destZipField;
            }
            set {
                this.destZipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string destPhone {
            get {
                return this.destPhoneField;
            }
            set {
                this.destPhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string destFax {
            get {
                return this.destFaxField;
            }
            set {
                this.destFaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string delivered {
            get {
                return this.deliveredField;
            }
            set {
                this.deliveredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string scac {
            get {
                return this.scacField;
            }
            set {
                this.scacField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string guaranteed {
            get {
                return this.guaranteedField;
            }
            set {
                this.guaranteedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string call {
            get {
                return this.callField;
            }
            set {
                this.callField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getTraceDataCompletedEventHandler(object sender, getTraceDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTraceDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTraceDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TraceResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TraceResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591